apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hx-monitor.fullname" . }}-monitor-config
  namespace: {{ include "hx-monitor.namespace" . }}
  labels:
    component: monitor
data:
  {{- with .Values.components.monitor.config.env }}
  USE_TWILIO_TRANSCRIPTION: "{{ .USE_TWILIO_TRANSCRIPTION }}"
  USE_WHISPER_TRANSCRIPTION: "{{ .USE_WHISPER_TRANSCRIPTION }}"
  TWILIO_PARTIAL_TRANSCRIPTIONS: "{{ .TWILIO_PARTIAL_TRANSCRIPTIONS }}"
  WHISPER_MODEL: "{{ .WHISPER_MODEL }}"
  WHISPER_MODELS_PATH: "{{ .WHISPER_MODELS_PATH }}"
  WHISPER_DO_MODEL_DOWNLOAD: "{{ .WHISPER_DO_MODEL_DOWNLOAD }}"
  TWILIO_CALL_LENGTH: "{{ .TWILIO_CALL_LENGTH }}"
  {{- end }}
  TWILIO_API_CALLBACK_URL: {{ include "hx-monitor.ngrokOrIngressUrl" . }}