apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hx-monitor.fullname" . }}-mongo-config
  namespace: {{ include "hx-monitor.namespace" . }}
  labels:
    component: monitor
data:
  {{- with .Values.mongoDb }}
  MONGO_HOST: {{ .host | quote  }}
  MONGO_PORT: {{ .port | quote  }}
  MONGO_USER: {{ .username | quote }}
  MONGODB_DATABASE: {{ .database | quote }}
  {{- if .authDatabase }}
  MONGODB_AUTH_DATABASE: {{ .authDatabase | quote }}
  {{- end }}
  {{- end }}