apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hx-monitor.fullname" . }}-monitor
  namespace: {{ include "hx-monitor.namespace" . }}
  labels:
    component: monitor
    {{- include "hx-monitor.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: monitor
      {{- include "hx-monitor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        component: monitor
        {{- include "hx-monitor.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hx-monitor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: monitor
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.components.monitor.image.repository }}:{{ .Values.components.monitor.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ include "hx-monitor.fullname" . }}-monitor-config
          - configMapRef:
              name: {{ include "hx-monitor.fullname" . }}-mongo-config
          - secretRef:
              name: {{ include "hx-monitor.twilioCredentialsSecretName" . }}
          {{- if .Values.components.monitor.config.ngrok.enable }}
          - secretRef:
              name: {{ include "hx-monitor.ngrokCredentialsSecretName" . }}
          {{- end }}
          env:
          {{- with .Values.mongoDb }}
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .secretName }}
                key: mongodb-passwords
          {{- end }}
          {{- with .Values.podEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          ports:
            - name: callback
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: whisper-models
              mountPath: /opt/models_whisper
      volumes:
        - name: whisper-models
          persistentVolumeClaim:
            claimName: {{ include "hx-monitor.fullname" . }}-monitor-whisper
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}