apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hx-monitor.fullname" . }}-frontend
  namespace: {{ include "hx-monitor.namespace" . }}
  labels:
    component: frontend
    {{- include "hx-monitor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.components.frontend.replicas }}
  selector:
    matchLabels:
      component: frontend
      {{- include "hx-monitor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        component: frontend
        {{- include "hx-monitor.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hx-monitor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: frontend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.components.frontend.image.repository }}:{{ .Values.components.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: REACT_APP_API_BASE_URL
            value: {{ include "hx-monitor.ingressUrl" . }}
          {{- if .Values.components.frontend.config.airspacesJsonUrl }}
          - name: REACT_APP_AIRPSACES_JSON_URL
            value: {{ .Values.components.frontend.config.airspacesJsonUrl | quote }}
          {{- end }}
          - name: REACT_APP_PRE_FILTER_GEO_JSON
            value: {{ .Values.components.frontend.config.filterGeoJson | quote }}
          {{- with .Values.podEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}