apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hx-monitor.fullname" . }}
  namespace: {{ include "hx-monitor.namespace" . }}
  labels:
    {{- include "hx-monitor.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  {{- with .Values.ingress }}
  tls:
    - hosts:
        - {{ .host | quote }}
      secretName: {{ .tls.secretName | default "frontend" }}-ingress-cert
  {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /callback
            pathType: Prefix
            backend:
              service:
                name: {{ include "hx-monitor.fullname" . }}-monitor
                port:
                  name: callback
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "hx-monitor.fullname" . }}-api
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "hx-monitor.fullname" . }}-frontend
                port:
                  name: http