{{- if .Values.mongoDb.seedDatabase }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hx-monitor.fullname" . }}-mongodb-seed
  namespace: {{ include "hx-monitor.namespace" . }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    spec:
      containers:
        - name: mongodb-seed
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              TIMEOUT=2m
              PRIMARY_POD=pod/mongodb-0
              echo "Waiting $TIMEOUT for '$PRIMARY_POD' to become ready..."
              kubectl -n {{ include "hx-monitor.namespace" . }} wait --for=condition=Ready $PRIMARY_POD --timeout=$TIMEOUT
              [ $? -ne 0 ] && exit 1

              kubectl -n $THIS_NAMESPACE exec $PRIMARY_POD -- sh -c 'mongosh "mongodb://localhost:$MONGODB_PORT_NUMBER" -u "$MONGODB_EXTRA_USERNAMES" -p "$MONGODB_EXTRA_PASSWORDS" --authenticationDatabase "$MONGODB_EXTRA_DATABASES" --eval "$(cat <<EOF
              conn = db.getMongo()
              db = conn.getDB("$MONGODB_EXTRA_DATABASES");

              db.calls.drop()
              db.numbers.drop()
              db.hx_areas.drop()
              db.hx_sub_areas.drop()

              db.numbers.insertMany([
                { name: "meiringen", number: "+41800496347" }
              ])

              db.hx_areas.insertMany([
                {
                  name: "meiringen",
                  number_name: "meiringen",
                  sub_areas: [
                    {
                      full_name: "CTR Meiringen HX",
                      name: "meiringen-ctr",
                      active: false
                    }, {
                      full_name: "TMA Meiringen 1 HX",
                      name: "meiringen-tma-1",
                      active: false
                    }, {
                      full_name: "TMA Meiringen 2 HX",
                      name: "meiringen-tma-2",
                      active: false
                    }, {
                      full_name: "TMA Meiringen 3 HX",
                      name: "meiringen-tma-3",
                      active: false
                    }, {
                      full_name: "TMA Meiringen 4 HX",
                      name: "meiringen-tma-4",
                      active: false
                    }, {
                      full_name: "TMA Meiringen 5 HX",
                      name: "meiringen-tma-5",
                      active: false
                    }, {                     
                      full_name: "TMA Meiringen 6 HX",
                      name: "meiringen-tma-6",
                      active: false
                    }
                  ]
                },
              ])
              EOF
              )"'
          env:
            - name: THIS_NAMESPACE
              value: {{ include "hx-monitor.namespace" . }}
      restartPolicy: Never
      serviceAccountName: mongodb-seed-sa
  backoffLimit: 2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-seed-sa
  namespace: {{ include "hx-monitor.namespace" . }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mongodb-seed-role
  namespace: {{ include "hx-monitor.namespace" . }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongodb-seed-rb
  namespace: {{ include "hx-monitor.namespace" . }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
subjects:
  - kind: ServiceAccount
    name: mongodb-seed-sa
    namespace: {{ include "hx-monitor.namespace" . }}
roleRef:
  kind: Role
  name: mongodb-seed-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
