{{- if .Values.components.monitor.config.ngrok.enable }}
{{- if .Values.components.monitor.config.ngrok.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hx-monitor.fullname" . }}-monitor-ngrok
  namespace: {{ include "hx-monitor.namespace" . }}
stringData:
  NGROK_AUTH: {{ .Values.components.monitor.config.ngrok.authToken }}
{{- end }}
{{- end }}