{{- if .Values.components.monitor.config.twilio.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hx-monitor.twilioCredentialsSecretName" . }}
  namespace: {{ include "hx-monitor.namespace" . }}
stringData:
  {{- with .Values.components.monitor.config.twilio.secret }}
  TWILIO_ACCOUNT_SID: {{ .accountSid }}
  TWILIO_AUTH_TOKEN: {{ .authToken }}
  TWILIO_API_KEY: {{ .apiKey }}
  TWILIO_API_SECRET: {{ .apiSecret }}
  TWILIO_CALL_FROM: {{ .callFrom | quote }}
  {{- end }}
{{- end }}