apiVersion: v1
kind: Service
metadata:
  name: {{ include "hx-monitor.fullname" . }}-monitor
  namespace: {{ include "hx-monitor.namespace" . }}
  labels:
    component: monitor
    {{- include "hx-monitor.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: callback
      protocol: TCP
      name: callback
  selector:
    component: monitor
