apiVersion: v1
kind: Service
metadata:
  name: {{ include "hx-monitor.fullname" . }}-api
  namespace: {{ include "hx-monitor.namespace" . }}
  labels:
    component: api
    {{- include "hx-monitor.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    component: api
