apiVersion: v1
kind: Service
metadata:
  name: {{ include "hx-monitor.fullname" . }}-frontend
  labels:
    component: frontend
    {{- include "hx-monitor.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    component: frontend
