nameOverride: ""
fullnameOverride: ""

# -------------------------------
# -- HX-Monitor core components
# @default -- Component specification, see below for defaults
components:
  monitor:
    # replicas: 1 - >1 Not yet supported
    image:
      repository: thisisnttheway/hx-monitor-service
      tag: "latest"
    config:
      # -- Only envs as specified below will be templated
      env:
        USE_TWILIO_TRANSCRIPTION: 1
        USE_WHISPER_TRANSCRIPTION: 0
        TWILIO_PARTIAL_TRANSCRIPTIONS: 0
        WHISPER_MODEL: tiny.en
        WHISPER_MODELS_PATH: ./models_whisper
        WHISPER_DO_MODEL_DOWNLOAD: 1
        TWILIO_CALL_LENGTH: 36
        # TWILIO_CALLBACK_URL will be dynamically set
      # -- ngrok config
      ngrok:
        enable: create
        secret:
          # -- Create secret. Set to 'false' if you bring your own secret
          #    Must have key "NGROK_AUTH"
          create: true
          # -- Name of your own custom secret
          name: ""
          # -- ngrok auth token, used if 'create: true'
          authToken: ""
      whisper:
        # -- PVC used for whisper models
        pvc:
          # -- Create PVC. Set to 'false' if you bring your own
          create: true
          # -- Name of your own custom PVC
          name: ""
          # -- The following fields are only used if 'create: true'
          storageClass: ""
          size: 1Gi
  api:
    replicas: 1
    image:
      repository: thisisnttheway/hx-monitor-api-backend
      tag: "latest"
  frontend:
    config:
        # -- Uses SHV hosted JSON if left empty
        airspacesJsonUrl: ""
    replicas: 1
    image:
      repository: thisisnttheway/hx-monitor-frontend
      tag: "latest"

# -- MongoDB config
mongoDb:
  # -- Name of MongoDB secret containing the password
  #    It needs the key "mongodb-passwords"
  secretName: ""
  # -- MongoDB username
  username: ""
  # -- MongoDB host
  host: ""
  # -- MongoDB port
  port: 27017
  # -- HX monitor database name
  database: "hx"

# -------------------------------
# -- Global image definitions
image:
  pullPolicy: IfNotPresent
imagePullSecrets: []

# -- Ingress configuration, opiniated
ingress:
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # -- Host used for the ingress object (also TLS)
  host: chart-example.local
  tls:
    # -- Enable TLS
    enabled: true
    # -- Certificate secret
    secretName: ""

# -------------------------------
# -- Global pod configs
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# -- Pods resource constraints
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- Pods node selector
nodeSelector: {}

# -- Pods tolerations
tolerations: []

# -- Pods affinities
affinity: {}
